# Generated by Django 5.2.7 on 2026-07-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Unpaid', max_length=20),
        ),
    ]
